-- État actuel de la migration
SELECT 'USER.auth type' AS check_name,
       COLUMN_TYPE AS result
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='USER' AND COLUMN_NAME='auth'
UNION ALL
SELECT 'CHANNEL_LOG.publictext type',
       COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='CHANNEL_LOG' AND COLUMN_NAME='publictext'
UNION ALL
SELECT 'USER.hostmasks column exists',
       CASE WHEN COUNT(*)>0 THEN 'YES (not yet renamed)' ELSE 'renamed to hostmasks_legacy' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='USER' AND COLUMN_NAME='hostmasks'
UNION ALL
SELECT 'USER.hostmasks_legacy exists',
       CASE WHEN COUNT(*)>0 THEN 'YES (migration done)' ELSE 'NO' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='USER' AND COLUMN_NAME='hostmasks_legacy'
UNION ALL
SELECT 'USER_HOSTMASK table exists',
       CASE WHEN COUNT(*)>0 THEN 'YES' ELSE 'NO (failed)' END
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='USER_HOSTMASK'
UNION ALL
SELECT 'USER.id_user type',
       COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='USER' AND COLUMN_NAME='id_user'
UNION ALL
SELECT 'FK count in mediabotv3',
       CAST(COUNT(*) AS CHAR)
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA='mediabotv3' AND REFERENCED_TABLE_NAME IS NOT NULL
UNION ALL
SELECT 'WEBLOG.password exists',
       CASE WHEN COUNT(*)>0 THEN 'YES (not dropped)' ELSE 'NO (dropped OK)' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='mediabotv3' AND TABLE_NAME='WEBLOG' AND COLUMN_NAME='password';
