# =============================================================================
#  test.conf.tpl — Template de configuration pour les tests live Mediabot
#  Généré automatiquement par test_live.pl — NE PAS ÉDITER MANUELLEMENT
#  Les valeurs {{PLACEHOLDER}} sont substituées au moment de l'exécution.
# =============================================================================

[openai]
API_KEY=

[mysql]
MAIN_PROG_DBUSER=mediabot_test
MAIN_PROG_DBHOST={{DBHOST}}
MAIN_PROG_DBPASS=
MAIN_PROG_DDBNAME=mediabot_test
MAIN_PROG_DBPORT={{DBPORT}}
CHARSET_MODE=utf8mb4

[hailo]
HAILO_LEARN_MAX_WORDS=20
HAILO_LEARN_MIN_WORDS=3

[radio]
YOUTUBEDL_INCOMING=/tmp
YTDLP_PATH=/usr/bin/yt-dlp
RADIO_ICECAST_STATUS_BASE_URL=http://127.0.0.1:8000
RADIO_ICECAST_PUBLIC_BASE_URL=http://127.0.0.1:8000
RADIO_ICECAST_TIMEOUT=5
RADIO_ICECAST_PRIMARY_MOUNT=/radio160.mp3

[connection]
CONN_NICK={{BOTNICK}}
CONN_SERVER_NETWORK=TestNetwork
CONN_IRCNAME=mediabot_test
CONN_NETWORK_TYPE=1
CONN_USERMODE=+i
CONN_USERNAME=mediabot
CONN_PASS=
CONN_BIND_IP=

[undernet]
UNET_CSERVICE_USERNAME=
UNET_CSERVICE_PASSWORD=
UNET_CSERVICE_LOGIN=

[main]
MAIN_PROG_NAME=Mediabot
MAIN_PROG_MAXLEN=400
MAIN_PROG_CMD_CHAR={{CMDCHAR}}
MAIN_PROG_URL=
MAIN_PROG_BIRTHDATE=1556692931
MAIN_PID_FILE=/tmp/mediabot_test.pid
MAIN_PROG_QUIT_MSG=Test shutdown
MAIN_LOG_FILE={{LOGFILE}}
MAIN_PROG_LIVE=1
MAIN_PROG_DEBUG=0
EXEC_TIMEOUT_SECONDS=8
MAIN_PROG_INITIAL_TRIGGER=1
MAIN_CHANNEL_NICKLIST_REFRESH_INTERVAL=300
YOUTUBE_APIKEY=
NICK_TRIGGER=1
RANDOM_QUOTE=900
PARTYLINE_PORT={{PARTYLINE_PORT}}
RECONNECT_DELAY=5
CHANNEL_LOG_RETENTION_DAYS=90
USER_SEEN_RETENTION_DAYS=180
DCC_DEBUG_HINTS=0
PARTYLINE_EVAL_ENABLED=0
PARTYLINE_EVAL_TIMEOUT_SECONDS=5

[metrics]
METRICS_ENABLED=0
METRICS_BIND=127.0.0.1
METRICS_PORT=9108

[libera]
LIBERA_NICKSERV_PASSWORD=

[fortnite]
API_KEY=

[tmdb]
API_KEY=
