# t/cases/111_configure_connection_optional_keys.t
# =============================================================================
# Regression checks for optional [connection] keys generated by install/configure.pl.
#
# Runtime code reads:
#   connection.CONN_PASS
#   connection.CONN_BIND_IP
#
# The root sample config, live template, and generated config flow should all
# expose those keys with empty defaults.
# =============================================================================

use strict;
use warnings;

BEGIN {
    use FindBin qw($Bin);
    unshift @INC, "$Bin/../lib";
    unshift @INC, "$Bin/../..";
}

use File::Spec;

sub _slurp_connection_optional_keys {
    my ($path) = @_;

    open my $fh, '<:encoding(UTF-8)', $path or die "cannot read $path: $!";
    local $/;
    return <$fh>;
}

sub _section_body_connection_optional_keys {
    my ($src, $section) = @_;

    my ($body) = $src =~ /^\[\Q$section\E\]\s*\n(.*?)(?=^\[[^\]]+\]\s*$|\z)/ms;
    return $body;
}

return sub {
    my ($assert) = @_;

    my $configure = _slurp_connection_optional_keys(
        File::Spec->catfile('.', 'install', 'configure.pl')
    );

    my $main = _slurp_connection_optional_keys(
        File::Spec->catfile('.', 'mediabot.pl')
    );

    my $core = _slurp_connection_optional_keys(
        File::Spec->catfile('.', 'Mediabot', 'Mediabot.pm')
    );

    my $runtime = $main . "\n" . $core;

    my $sample = _slurp_connection_optional_keys(
        File::Spec->catfile('.', 'mediabot.sample.conf')
    );

    my $live = _slurp_connection_optional_keys(
        File::Spec->catfile('.', 't', 'live', 'test.conf.tpl')
    );

    my $sample_connection = _section_body_connection_optional_keys($sample, 'connection');
    my $live_connection   = _section_body_connection_optional_keys($live, 'connection');

    $assert->like(
        $runtime,
        qr/get\('connection\.CONN_PASS'\)/,
        'runtime reads connection.CONN_PASS'
    );

    $assert->like(
        $runtime,
        qr/get\('connection\.CONN_BIND_IP'\)/,
        'runtime reads connection.CONN_BIND_IP'
    );

    $assert->like(
        $configure,
        qr/print CONF "CONN_PASS=\$line\\n"/,
        'install/configure.pl writes CONN_PASS'
    );

    $assert->like(
        $configure,
        qr/print CONF "CONN_BIND_IP=\$line\\n"/,
        'install/configure.pl writes CONN_BIND_IP'
    );

    $assert->like(
        $configure,
        qr/Enter IRC server password \(Enter to leave it empty\)/,
        'install/configure.pl prompts for optional IRC server password'
    );

    $assert->like(
        $configure,
        qr/Enter local bind IP \(Enter to leave it empty\)/,
        'install/configure.pl prompts for optional local bind IP'
    );

    $assert->like(
        $sample_connection // '',
        qr/^CONN_PASS=$/m,
        'sample config defines empty CONN_PASS'
    );

    $assert->like(
        $sample_connection // '',
        qr/^CONN_BIND_IP=$/m,
        'sample config defines empty CONN_BIND_IP'
    );

    $assert->like(
        $live_connection // '',
        qr/^CONN_PASS=$/m,
        'live template defines empty CONN_PASS'
    );

    $assert->like(
        $live_connection // '',
        qr/^CONN_BIND_IP=$/m,
        'live template defines empty CONN_BIND_IP'
    );
};
