use strict;
use warnings;
use Mediabot::Mediabot;
use Mediabot::Context;
use Mediabot::BuiltinCommandCatalog qw(public_command_names);
use MB813RandomQuoteFixture;
use MockMessage;
return sub {
    my ($a)=@_;my $f=MB813RandomQuoteFixture->new;my $bot=$f->{bot};my $p=$f->{state};
    my %handlers=Mediabot::_builtin_public_command_handlers();
    $a->ok($handlers{randomquote},'mb813: randomquote is registry-native');
    my %private=Mediabot::_builtin_private_command_handlers();
    $a->ok($private{randomquote},'mb813: private registry also supports explicit channel');
    $a->ok(grep({$_ eq 'randomquote'} public_command_names()),'mb813: randomquote included in catalogue');
    my (@acl,$permission);$permission=1;
    no warnings 'redefine';
    local *Mediabot::RandomQuote::Commands::checkUserChannelLevel=sub{push @acl,[$_[2],$_[4]];return $permission};
    my $ctx=Mediabot::Context->new(bot=>$bot,nick=>'Teuk',channel=>'#console',command=>'randomquote',message=>MockMessage->new,args=>[]);
    my $run=sub{$bot->reset_replies;$ctx->{args}=[@_];$handlers{randomquote}->($ctx);return $bot->first_reply_text};
    $a->like($run->('#test'),qr/\+RandomQuote on; every 180m \(default\); 2 quote/,'mb813: status exposes flag/default/quote count');
    $a->ok(!-e "$f->{dir}/state.json",'mb813: status remains read-only');
    $a->like($run->('#test','every','60m'),qr/every 60m \(channel setting\)/,'mb813: explicit console frequency accepted');
    $a->is($p->status('#test',10800)->{interval},3600,'mb813: frequency stored in seconds');
    $a->is($p->status('#other',10800)->{interval},10800,'mb813: unrelated channel unchanged');
    $a->is($bot->{replies}[0]{type},'notice','mb813: command response stays private');
    $a->is($bot->{replies}[0]{to},'Teuk','mb813: no control chatter in destination channel');
    $run->('#other','every','2h');
    $a->like($bot->first_reply_text,qr/\+RandomQuote off; every 120m/,'mb813: frequency does not enable disabled channel');
    $a->is($f->{dbh}->selectrow_array('SELECT COUNT(*) FROM CHANNEL_SET WHERE id_channel=2'),0,'mb813: no chanset mutation');
    $run->('#test','45');$a->is($p->status('#test',10800)->{interval},2700,'mb813: bare number means minutes');
    $run->('#test','every','7d');$a->is($p->status('#test',10800)->{interval},604800,'mb813: maximum seven days');
    $run->('#test','every','15m');$a->is($p->status('#test',10800)->{interval},900,'mb813: minimum fifteen minutes');
    for my $args (['every','14m'],['every','8d'],['every','0'],['every'],['on'],['now'],['every','60m','extra'],['status','extra'],['default','extra']) {
        $a->like($run->('#test',@$args),qr/^Syntax:/,'mb813: unsupported or malformed command gives syntax');
    }
    $a->is($p->status('#test',10800)->{interval},900,'mb813: bad commands preserve current frequency');
    $run->('#test','default');$a->ok(!$p->status('#test',10800)->{custom},'mb813: default resets override');
    $a->is($p->status('#test',10800)->{interval},10800,'mb813: reset uses configured/fallback frequency');
    $ctx->{channel}='#test';$run->('every','2h');
    $a->is($p->status('#test',10800)->{interval},7200,'mb813: in-channel form uses current channel');
    $ctx->{channel}=undef;$a->like($run->('every','60m'),qr/^Syntax:/,'mb813: private context needs explicit target');
    $a->like($run->('#test','status'),qr/every 120m/,'mb813: explicit target usable in private context');
    $bot->reset_replies;$ctx->{args}=['#test','status'];$private{randomquote}->($ctx);
    $a->like($bot->first_reply_text,qr/every 120m/,'mb813: real private handler delegates with target');
    $a->like($run->('#missing','every','60m'),qr/not registered/,'mb813: unregistered target rejected');
    $a->ok(!$p->status('#missing',10800)->{custom},'mb813: unregistered target creates no policy');
    $ctx->{channel}='#console';$bot->set_mock_user(MockUser->new(auth=>1,level=>'User'));
    delete @{$ctx}{qw(user _user_fetched)};
    $run->('#test','every','60m');
    $a->is(join('|',@{$acl[-1]}),'#test|450','mb813: console operation checks target level 450');
    $permission=0;$a->like($run->('#test','every','30m'),qr/requires Administrator/,'mb813: target ACL denial is explicit');
    $a->is($p->status('#test',10800)->{interval},3600,'mb813: target denial cannot change schedule');
    $a->like($run->('#test'),qr/requires Administrator/,'mb813: status also follows target ACL');
    $bot->set_mock_user(MockUser->new(auth=>0,level=>'User'));delete @{$ctx}{qw(user _user_fetched)};
    $a->like($run->('#test','every','30m'),qr/You must be logged/,'mb813: unidentified caller cannot configure');
    $a->is($p->status('#test',10800)->{interval},3600,'mb813: auth failure preserves state');
    $a->is($f->{dbh}->selectrow_array('SELECT SUM(hits) FROM QUOTES'),0,'mb813: configuration/status do not change quote counters');
};
