#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

use Cwd qw(abs_path);
use File::Basename qw(dirname);
use File::Spec;
use FindBin qw($Bin);
use Getopt::Long qw(GetOptions);
use lib "$Bin/..";
use Mediabot::BuiltinCommandCatalog qw(
    public_command_names
    private_command_names
    direct_public_command_names
);

binmode STDOUT, ':encoding(UTF-8)';
binmode STDERR, ':encoding(UTF-8)';

my ($write_path, $check_path, $help);
GetOptions(
    'write=s' => \$write_path,
    'check=s' => \$check_path,
    'help'    => \$help,
) or _usage(2);

_usage(0) if $help;
die "--write and --check are mutually exclusive\n"
    if defined $write_path && defined $check_path;
die "unexpected arguments: @ARGV\n" if @ARGV;

my $root = abs_path(File::Spec->catdir($Bin, '..'));
die "cannot resolve project root\n" unless defined $root;

my $source_path = File::Spec->catfile($root, 'Mediabot', 'Mediabot.pm');
my $version_path = File::Spec->catfile($root, 'VERSION');
my $source = _slurp($source_path);
my $version = _slurp($version_path);
$version =~ s/\s+\z//;
$version =~ s/\A(.+?dev)-\d{8}_\d{6}\z/$1/;

my ($help_block) = $source =~
    /my\s+\$raw\s*=\s*<<'MEDIABOT_INTERNAL_HELP';\n(.*?)\nMEDIABOT_INTERNAL_HELP/s;
die "cannot locate MEDIABOT_INTERNAL_HELP\n" unless defined $help_block;

my $public_sub  = _sub_body($source, '_builtin_public_command_handlers');
my $private_sub = _sub_body($source, '_builtin_private_command_handlers');

die "cannot locate _builtin_public_command_handlers\n" unless defined $public_sub;
die "cannot locate _builtin_private_command_handlers\n" unless defined $private_sub;

my %public_handlers  = _handler_commands($public_sub);
my %private_handlers = _handler_commands($private_sub);
my %registry_public = map { $_ => 1 } public_command_names();
my %registry_private = map { $_ => 1 } private_command_names();
my %direct_public = map { $_ => 1 } direct_public_command_names();

_assert_same_keys('public registry handler catalogue', \%public_handlers, \%registry_public);
_assert_same_keys('private registry handler catalogue', \%private_handlers, \%registry_private);
_assert_same_keys('direct public registry catalogue', \%direct_public, \%registry_public);

my %known_level = map { lc($_) => 1 } (
    'public', 'private', 'admin', 'owner', 'master', 'authorized',
    'operator+', 'channel admin', 'private/admin', 'administrator',
);

my (%entries, @duplicate, @parser_anomaly);
for my $line (split /\n/, $help_block) {
    next if $line =~ /^\s*$/;
    next if $line =~ /^\s*#/;

    my @fields = split /\|/, $line;
    my $command = shift @fields;
    my $description = pop @fields;
    my $level = pop @fields;
    my $syntax = join '|', @fields;

    next unless defined $command && length $command;

    if (exists $entries{lc $command}) {
        push @duplicate, lc $command;
        next;
    }

    my $key = lc $command;
    my $note = '';
    unless (defined $level && $known_level{lc $level}) {
        $note = 'legacy help parser sees an unexpected level; an unescaped pipe is present';
        push @parser_anomaly, $key;
    }

    my @surfaces;
    push @surfaces, 'registry-public'  if $registry_public{$key};
    push @surfaces, 'registry-private' if $registry_private{$key};
    push @surfaces, 'help-only'      unless @surfaces;

    $entries{$key} = {
        command     => $key,
        syntax      => defined($syntax) && length($syntax) ? $syntax : $key,
        level       => defined($level) && length($level) ? $level : 'unknown',
        description => defined($description) && length($description)
            ? $description : 'No description available yet.',
        surfaces    => join(', ', @surfaces),
        note        => $note,
    };
}

my @help_only = sort grep {
    $entries{$_}{surfaces} eq 'help-only'
} keys %entries;

my @undocumented_public = sort grep {
    !exists $entries{$_}
} keys %public_handlers;

my @undocumented_private = sort grep {
    !exists $entries{$_}
} keys %private_handlers;

my $markdown = '';
$markdown .= "# Built-in command inventory\n\n";
$markdown .= "> Generated by `tools/mb_architecture_inventory.pl` from "
    . "`Mediabot/Mediabot.pm`. Do not edit this file by hand.\n\n";
$markdown .= "Source version line: `$version`\n\n";
$markdown .= "## Catalogue baseline\n\n";
$markdown .= "| Measure | Count |\n| --- | ---: |\n";
$markdown .= "| Internal help entries | " . scalar(keys %entries) . " |\n";
$markdown .= "| Registered public built-ins | " . scalar(keys %registry_public) . " |\n";
$markdown .= "| Registered private built-ins | " . scalar(keys %registry_private) . " |\n";
$markdown .= "| Direct public registry handlers | " . scalar(keys %direct_public) . " |\n";
$markdown .= "| Direct private registry handlers | " . scalar(keys %private_handlers) . " |\n";
$markdown .= "| Compatibility dispatch tables | 0 |\n";
$markdown .= "| Help parser anomalies | " . scalar(@parser_anomaly) . " |\n";
$markdown .= "| Help-only entries | " . scalar(@help_only) . " |\n";
$markdown .= "| Undocumented public handlers | " . scalar(@undocumented_public) . " |\n";
$markdown .= "| Undocumented private handlers | " . scalar(@undocumented_private) . " |\n\n";

$markdown .= "`CommandRegistry` is the authority for every built-in command. "
    . "Each catalogue entry stores its executable handler, so dispatch performs no "
    . "second lookup in a compatibility hash. Adding or removing a handler without "
    . "updating the catalogue makes this generator fail. Database-backed dynamic "
    . "commands are instance data and are intentionally "
    . "excluded.\n\n";

if (@parser_anomaly) {
    $markdown .= "### Known baseline anomalies\n\n";
    $markdown .= "The runtime parser found unexpected help levels, usually caused by "
        . "unescaped `|` characters in descriptions. Affected entries: "
        . join(', ', map { "`$_`" } @parser_anomaly) . ".\n\n";
}

$markdown .= "## Commands\n\n";
$markdown .= "| Command | Effective level | Dispatch surfaces | Syntax | Description | Note |\n";
$markdown .= "| --- | --- | --- | --- | --- | --- |\n";
for my $command (sort keys %entries) {
    my $entry = $entries{$command};
    $markdown .= '| ' . join(' | ', map { _md($_) } (
        "`$entry->{command}`",
        $entry->{level},
        $entry->{surfaces},
        "`$entry->{syntax}`",
        $entry->{description},
        $entry->{note},
    )) . " |\n";
}

if (defined $check_path) {
    my $full = _resolve_output_path($root, $check_path);
    my $existing = _slurp($full);
    die "command inventory is stale: $check_path\n"
        unless $existing eq $markdown;
    print "PASS  command inventory matches $check_path\n";
    exit 0;
}

if (defined $write_path) {
    my $full = _resolve_output_path($root, $write_path);
    open my $fh, '>:encoding(UTF-8)', $full
        or die "cannot write $full: $!\n";
    print {$fh} $markdown;
    close $fh or die "cannot close $full: $!\n";
    print "WROTE $write_path\n";
    exit 0;
}

print $markdown;
exit 0;

sub _usage {
    my ($code) = @_;
    print <<'USAGE';
Usage:
  tools/mb_architecture_inventory.pl
  tools/mb_architecture_inventory.pl --write docs/generated/COMMAND_INVENTORY.md
  tools/mb_architecture_inventory.pl --check docs/generated/COMMAND_INVENTORY.md

Without an option, the generated Markdown is written to STDOUT.
USAGE
    exit $code;
}

sub _slurp {
    my ($path) = @_;
    open my $fh, '<:encoding(UTF-8)', $path
        or die "cannot read $path: $!\n";
    local $/;
    my $text = <$fh>;
    close $fh;
    return $text;
}

sub _sub_body {
    my ($text, $name) = @_;
    return undef unless $text =~ /^sub\s+\Q$name\E\s*\{/mg;

    my $start = pos $text;
    my $depth = 1;
    my $pos = $start;
    my $length = length $text;

    while ($pos < $length) {
        my $char = substr $text, $pos, 1;
        $depth++ if $char eq '{';
        $depth-- if $char eq '}';
        return substr($text, $start, $pos - $start) if $depth == 0;
        $pos++;
    }

    return undef;
}

sub _handler_commands {
    my ($body) = @_;
    my %commands;
    while ($body =~ /^\s*'?([a-z0-9_]+)'?\s*=>\s*sub\b/mg) {
        $commands{$1} = 1;
    }
    return %commands;
}

sub _assert_same_keys {
    my ($label, $actual, $expected) = @_;

    my @added = sort grep { !$expected->{$_} } keys %$actual;
    my @missing = sort grep { !$actual->{$_} } keys %$expected;
    return 1 unless @added || @missing;

    die "$label drift: added=[" . join(',', @added) . "] missing=["
        . join(',', @missing) . "]\n";
}

sub _resolve_output_path {
    my ($project_root, $path) = @_;
    return $path if File::Spec->file_name_is_absolute($path);
    return File::Spec->catfile($project_root, split m{/}, $path);
}

sub _md {
    my ($value) = @_;
    $value = '' unless defined $value;
    $value =~ s/\r?\n/ /g;
    $value =~ s/\|/\\|/g;
    return $value;
}
