#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

use Cwd qw(abs_path);
use File::Basename qw(dirname);
use File::Spec;
use FindBin qw($Bin);
use Getopt::Long qw(GetOptions);

binmode STDOUT, ':encoding(UTF-8)';
binmode STDERR, ':encoding(UTF-8)';

my ($write_path, $check_path, $help);
GetOptions(
    'write=s' => \$write_path,
    'check=s' => \$check_path,
    'help'    => \$help,
) or _usage(2);

_usage(0) if $help;
die "--write and --check are mutually exclusive\n"
    if defined $write_path && defined $check_path;
die "unexpected arguments: @ARGV\n" if @ARGV;

my $root = abs_path(File::Spec->catdir($Bin, '..'));
die "cannot resolve project root\n" unless defined $root;

my $source_path = File::Spec->catfile($root, 'Mediabot', 'Mediabot.pm');
my $version_path = File::Spec->catfile($root, 'VERSION');
my $source = _slurp($source_path);
my $version = _slurp($version_path);
$version =~ s/\s+\z//;

my ($help_block) = $source =~
    /my\s+\$raw\s*=\s*<<'MEDIABOT_INTERNAL_HELP';\n(.*?)\nMEDIABOT_INTERNAL_HELP/s;
die "cannot locate MEDIABOT_INTERNAL_HELP\n" unless defined $help_block;

my $public_sub  = _sub_body($source, 'mbCommandPublic');
my $private_sub = _sub_body($source, 'mbCommandPrivate');
my $builtin_sub = _sub_body($source, '_register_builtin_public_core_commands');

die "cannot locate mbCommandPublic\n" unless defined $public_sub;
die "cannot locate mbCommandPrivate\n" unless defined $private_sub;
die "cannot locate built-in registry bootstrap\n" unless defined $builtin_sub;

my %public_dispatch  = _dispatch_commands($public_sub,  'command_map');
my %private_dispatch = _dispatch_commands($private_sub, 'command_table');
my %registry = map { $_ => 1 }
    ($builtin_sub =~ /\bname\s*=>\s*'([a-z0-9_]+)'/g);

my %known_level = map { lc($_) => 1 } (
    'public', 'private', 'admin', 'owner', 'master', 'authorized',
    'operator+', 'channel admin', 'private/admin', 'administrator',
);

my (%entries, @duplicate, @parser_anomaly);
for my $line (split /\n/, $help_block) {
    next if $line =~ /^\s*$/;
    next if $line =~ /^\s*#/;

    my @fields = split /\|/, $line;
    my $command = shift @fields;
    my $description = pop @fields;
    my $level = pop @fields;
    my $syntax = join '|', @fields;

    next unless defined $command && length $command;

    if (exists $entries{lc $command}) {
        push @duplicate, lc $command;
        next;
    }

    my $key = lc $command;
    my $note = '';
    unless (defined $level && $known_level{lc $level}) {
        $note = 'legacy help parser sees an unexpected level; an unescaped pipe is present';
        push @parser_anomaly, $key;
    }

    my @surfaces;
    push @surfaces, 'registry'       if $registry{$key};
    push @surfaces, 'legacy-public'  if $public_dispatch{$key};
    push @surfaces, 'legacy-private' if $private_dispatch{$key};
    push @surfaces, 'help-only'      unless @surfaces;

    $entries{$key} = {
        command     => $key,
        syntax      => defined($syntax) && length($syntax) ? $syntax : $key,
        level       => defined($level) && length($level) ? $level : 'unknown',
        description => defined($description) && length($description)
            ? $description : 'No description available yet.',
        surfaces    => join(', ', @surfaces),
        note        => $note,
    };
}

my @help_only = sort grep {
    $entries{$_}{surfaces} eq 'help-only'
} keys %entries;

my @undocumented_public = sort grep {
    !exists $entries{$_}
} keys %public_dispatch;

my @undocumented_private = sort grep {
    !exists $entries{$_}
} keys %private_dispatch;

my $markdown = '';
$markdown .= "# Built-in command inventory\n\n";
$markdown .= "> Generated by `tools/mb_architecture_inventory.pl` from "
    . "`Mediabot/Mediabot.pm`. Do not edit this file by hand.\n\n";
$markdown .= "Source version: `$version`\n\n";
$markdown .= "## Baseline\n\n";
$markdown .= "| Measure | Count |\n| --- | ---: |\n";
$markdown .= "| Internal help entries | " . scalar(keys %entries) . " |\n";
$markdown .= "| Legacy public dispatch entries | " . scalar(keys %public_dispatch) . " |\n";
$markdown .= "| Legacy private dispatch entries | " . scalar(keys %private_dispatch) . " |\n";
$markdown .= "| Commands registered through `CommandRegistry` at boot | " . scalar(keys %registry) . " |\n";
$markdown .= "| Help parser anomalies | " . scalar(@parser_anomaly) . " |\n";
$markdown .= "| Help-only entries | " . scalar(@help_only) . " |\n";
$markdown .= "| Undocumented public dispatch entries | " . scalar(@undocumented_public) . " |\n";
$markdown .= "| Undocumented private dispatch entries | " . scalar(@undocumented_private) . " |\n\n";

$markdown .= "The inventory records the current source truth before MB741 unifies command "
    . "registration. `registry` is the new path; `legacy-public` and "
    . "`legacy-private` are compatibility dispatch tables. A command may appear on "
    . "more than one surface today. Database-backed dynamic commands are instance "
    . "data and are intentionally excluded.\n\n";

if (@parser_anomaly) {
    $markdown .= "### Known baseline anomalies\n\n";
    $markdown .= "The current runtime parser interprets unescaped `|` characters in "
        . "two help descriptions as field separators. MB740 records this truth but "
        . "does not alter IRC output; correction belongs to the command-catalogue "
        . "migration. Affected entries: "
        . join(', ', map { "`$_`" } @parser_anomaly) . ".\n\n";
}

$markdown .= "## Commands\n\n";
$markdown .= "| Command | Effective level | Dispatch surfaces | Syntax | Description | Note |\n";
$markdown .= "| --- | --- | --- | --- | --- | --- |\n";
for my $command (sort keys %entries) {
    my $entry = $entries{$command};
    $markdown .= '| ' . join(' | ', map { _md($_) } (
        "`$entry->{command}`",
        $entry->{level},
        $entry->{surfaces},
        "`$entry->{syntax}`",
        $entry->{description},
        $entry->{note},
    )) . " |\n";
}

if (defined $check_path) {
    my $full = _resolve_output_path($root, $check_path);
    my $existing = _slurp($full);
    die "command inventory is stale: $check_path\n"
        unless $existing eq $markdown;
    print "PASS  command inventory matches $check_path\n";
    exit 0;
}

if (defined $write_path) {
    my $full = _resolve_output_path($root, $write_path);
    open my $fh, '>:encoding(UTF-8)', $full
        or die "cannot write $full: $!\n";
    print {$fh} $markdown;
    close $fh or die "cannot close $full: $!\n";
    print "WROTE $write_path\n";
    exit 0;
}

print $markdown;
exit 0;

sub _usage {
    my ($code) = @_;
    print <<'USAGE';
Usage:
  tools/mb_architecture_inventory.pl
  tools/mb_architecture_inventory.pl --write docs/generated/COMMAND_INVENTORY.md
  tools/mb_architecture_inventory.pl --check docs/generated/COMMAND_INVENTORY.md

Without an option, the generated Markdown is written to STDOUT.
USAGE
    exit $code;
}

sub _slurp {
    my ($path) = @_;
    open my $fh, '<:encoding(UTF-8)', $path
        or die "cannot read $path: $!\n";
    local $/;
    my $text = <$fh>;
    close $fh;
    return $text;
}

sub _sub_body {
    my ($text, $name) = @_;
    return undef unless $text =~ /^sub\s+\Q$name\E\s*\{/mg;

    my $start = pos $text;
    my $depth = 1;
    my $pos = $start;
    my $length = length $text;

    while ($pos < $length) {
        my $char = substr $text, $pos, 1;
        $depth++ if $char eq '{';
        $depth-- if $char eq '}';
        return substr($text, $start, $pos - $start) if $depth == 0;
        $pos++;
    }

    return undef;
}

sub _dispatch_commands {
    my ($body, $table_name) = @_;
    my ($table) = $body =~ /my\s+%\Q$table_name\E\s*=\s*\((.*?)\n\s*\);/s;
    die "cannot locate %$table_name\n" unless defined $table;

    my %commands;
    while ($table =~ /^\s*'?([a-z0-9_]+)'?\s*=>\s*sub\b/mg) {
        $commands{$1} = 1;
    }
    return %commands;
}

sub _resolve_output_path {
    my ($project_root, $path) = @_;
    return $path if File::Spec->file_name_is_absolute($path);
    return File::Spec->catfile($project_root, split m{/}, $path);
}

sub _md {
    my ($value) = @_;
    $value = '' unless defined $value;
    $value =~ s/\r?\n/ /g;
    $value =~ s/\|/\\|/g;
    return $value;
}
